version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # entrypoint:
      # - sh
      # - -euc
      # - |
        # #[ ! -d /etc/prometheus/ ] && mkdir -p /etc/prometheus/
        # cat <<EOF > /etc/prometheus/prometheus.yml
        # global:
          # scrape_interval: 15s

        # scrape_configs:
          # - job_name: 'node'
            # static_configs:
              # - targets: ['rocky-linux.boldbi.com:9100']
          # - job_name: 'cadvisor'
            # static_configs:
              # - targets: ['rocky-linux.boldbi.com:8080']
        # EOF
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        #[ ! -d /etc/grafana/provisioning/datasources ] && mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/datasources.yaml
        apiVersion: 1
        datasources:
          - name: PROMETHEUS
            type: prometheus
            url: http://rocky-linux.boldbi.com:9090
            #uid: my-prometheus-uid
            #isDefault: true
        EOF
        #[ ! -d /etc/grafana/provisioning/dashboards ] && mkdir -p /etc/grafana/provisioning/dashboards
        cat <<EOF > /etc/grafana/provisioning/dashboards/dashboards.yaml
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: 'file'
            disableDeletion: false
            editable: true
            options:
              path: '/var/lib/grafana/dashboards'
        EOF
        /run.sh
    volumes:
      #- ./grafana/datasources:/etc/grafana/provisioning/datasources
      #- ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/custom-dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring-net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring-net

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    networks:
      - monitoring-net

networks:
  monitoring-net:
